Best/Controllers/AdminController.cs
using Best.Areas.Identity.Data;
using Best.Data.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Best.Controllers
{
    public class AdminController : Controller
    {
        private readonly UserManager<BestUser> _userManager;
        private readonly SignInManager<BestUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ICampaigns _campaigns;
        private readonly IPosts _posts;
        public AdminController( UserManager<BestUser> userManager, SignInManager<BestUser> signInManager, RoleManager<IdentityRole> roleManager, ICampaigns campaigns, IPosts posts)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;

            _campaigns = campaigns;
            _posts = posts;
        }
        public async Task<bool> IsAdmin()
        {
            var isAdmin = await _userManager.IsInRoleAsync(await _userManager.GetUserAsync(User), "Administrator");
            var isSignIn = _signInManager.IsSignedIn(User);
            if (!isSignIn || !isAdmin)
            {
                return false;
            }
            return true;
        }
        public async Task<IActionResult> Index()
        {
            if (!await IsAdmin()) return NotFound();
            return View();
        }
        public async Task<IActionResult> Campaigns()
        {
            if (!await IsAdmin()) return NotFound();
            return View(_campaigns.GetCampaigns.ToList());
        }
        public async Task<IActionResult> Posts()
        {
            if (!await IsAdmin()) return NotFound();
            return View(_posts.GetPosts.ToList());
        }
    }
}

Best/Controllers/CampaignsController.cs
using Best.Areas.Identity.Data;
using Best.Data;
using Best.Data.Interfaces;
using Best.Data.Models;
using Best.Data.Models.Rating;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Best.Controllers
{
    public class CampaignsController : Controller
    {
        private readonly ICampaigns _Campaigns;
        private readonly ITopics _topics;
        private readonly UserManager<BestUser> _userManager;
        private readonly SignInManager<BestUser> _signInManager;
        private readonly BestContent _context;
        public CampaignsController(ICampaigns Campaigns, ITopics topics, UserManager<BestUser> userManager, SignInManager<BestUser> signInManager, BestContent context)
        {
            _Campaigns = Campaigns;
            _topics = topics;
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }
        public IEnumerable<Campaign> GetCampaigns()
        {
            return _Campaigns.GetCampaigns;
        }
        public IActionResult Index()
        {
            return View(_Campaigns.GetCampaigns);
        }
        public IActionResult Create()
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Campaign Campaign)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return RedirectToAction(nameof(Index));
            }

            await _Campaigns.Create(Campaign);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Campaign = _Campaigns.GetCampaignById(id);

            if (Campaign == null)
            {
                return NotFound();
            }

            return View(Campaign);
        }
        public IActionResult Edit(string id)
        {
            if (!_signInManager.IsSignedIn(User) || id == null)
            {
                return NotFound();
            }

            var Campaign = _Campaigns.GetCampaignByIdForUser(_userManager.GetUserId(User), id);

            if (Campaign == null)
            {
                return NotFound();
            }

            return View(Campaign);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Campaign Campaign)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return RedirectToAction(nameof(Index));
            }

            await _Campaigns.Update(Campaign);

            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(Campaign);
        }
        public IActionResult Delete(string id)
        {
            if (!_signInManager.IsSignedIn(User) || id == null)
            {
                return NotFound();
            }

            var Campaign = _Campaigns.GetCampaignByIdForUser(_userManager.GetUserId(User), id);

            if (Campaign == null)
            {
                return NotFound();
            }

            return View(Campaign);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return RedirectToAction(nameof(Index));
            }

            await _Campaigns.Delete(id);

            return RedirectToAction(nameof(Index));
        }
        private bool CampaignExists(string id)
        {
            return _context.Topic.Any(e => e.Id == id);
        }
        public async Task<JsonResult> CampaignRating(string CampaignId, string UserId, string Rating)
        {
            var result = _context.CampaignRating.Where(l => l.Campaign.Id == CampaignId && l.BestUser.Id == UserId).ToList();
            if (result.Count != 0)
            {
                _context.CampaignRating.RemoveRange(result);
                await _context.SaveChangesAsync();
                return Json(false);
            }
            CampaignRating campaignRating = new CampaignRating();
            campaignRating.Campaign = await _context.Campaign.FirstOrDefaultAsync(p => p.Id == CampaignId);
            campaignRating.BestUser = await _context.BestUser.FirstOrDefaultAsync(u => u.Id == UserId);
            campaignRating.Rating = Convert.ToInt32(Rating);
            _context.Add(campaignRating);
            await _context.SaveChangesAsync();
            return Json(true);
        }
    }
}

Best/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Best.Data;
using Best.Data.Models;
using Best.Data.Interfaces;
using Best.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Best.Data.Models.Like;
using Best.Data.Interfaces.IComment;

namespace Best.Controllers
{
    public class PostsController : Controller
    {
        private readonly UserManager<BestUser> _userManager;
        private readonly SignInManager<BestUser> _signInManager;
        private readonly BestContent _context;
        private readonly IPosts _posts;
        private readonly IPostsComments _postsComments;
        private readonly ICampaigns _Campaigns;
        private readonly IBestUsers _bestUsers;

        public PostsController(BestContent context, IPosts posts, UserManager<BestUser> userManager, SignInManager<BestUser> signInManager, ICampaigns Campaigns, IBestUsers bestUsers, IPostsComments postsComments)
        {
            _context = context;

            _posts = posts;
            _postsComments = postsComments;

            _userManager = userManager;
            _signInManager = signInManager;
            _Campaigns = Campaigns;
            _bestUsers = bestUsers;
        }

        // GET: Posts
        public async Task<IActionResult> Index(string id)
        {
            if (id == null)
            {
                return View(_posts.GetPosts.ToList());
            }
            return View(_posts.GetPostsByCampaignId(id).ToList());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = _posts.GetPostById(id);
            post.Comments = post.Comments.OrderBy(d => d.CreateData);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public async Task<IActionResult> Create(string id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return NotFound();
            }
            return View(new Post() { CampaignId = id});
        }

        // POST: Posts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Post post)
        {
            if (ModelState.IsValid)
            {
                await _posts.Create(post);
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || !_signInManager.IsSignedIn(User))
            {
                return NotFound();
            }
            Post post = new Post();
            post = _posts.GetPostByIdForUser(_userManager.GetUserId(User), id);

            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                await _posts.Update(post);
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (!_signInManager.IsSignedIn(User) || id == null)
            {
                return NotFound();
            }

            Post post = _posts.GetPostByIdForUser(_userManager.GetUserId(User), id);

            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _posts.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(string id)
        {
            return _context.Post.Any(e => e.Id == id);
        }
        [HttpPost]
        public async Task<JsonResult> LikePost(string PostId, string UserId)
        {
            return Json(_posts.LikePost(PostId, UserId));
        }
        public async Task<JsonResult> AddComment(string Id, string UserId, string Text)
        {
            return Json(await _postsComments.AddComment(Id, UserId, Text));
        }
    }
}

Best/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Best.Data;
using Best.Data.Models;

namespace Best.Controllers
{
    public class TopicsController : Controller
    {
        private readonly BestContent _context;

        public TopicsController(BestContent context)
        {
            _context = context;
        }

        // GET: Topics
        public async Task<IActionResult> Index()
        {
            return View(await _context.Topic.ToListAsync());
        }

        // GET: Topics/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                return NotFound();
            }

            return View(topic);
        }

        // GET: Topics/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Topics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                if (!(_context.Topic.Any(t => t.Id == topic.Id) || _context.Topic.Any(t => t.Name == topic.Name)))
                {
                    _context.Add(topic);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }            
            }
            return View(topic);
        }

        // GET: Topics/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic.FindAsync(id);
            if (topic == null)
            {
                return NotFound();
            }
            return View(topic);
        }

        // POST: Topics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name")] Topic topic)
        {
            if (id != topic.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid && !_context.Topic.Any(t => t.Name == topic.Name))
            {
                try
                {
                    _context.Update(topic);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TopicExists(topic.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(topic);
        }

        // GET: Topics/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.Id == id);
            if (topic == null)
            {
                return NotFound();
            }

            return View(topic);
        }

        // POST: Topics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var topic = await _context.Topic.FindAsync(id);
            _context.Topic.Remove(topic);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TopicExists(string id)
        {
            return _context.Topic.Any(e => e.Id == id);
        }
    }
}

Best/Views/Shared/_Culture.cshtml
@inject IViewLocalizer Localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions

@{ 
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = locOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = x.Name }).ToList();
}
<form asp-action="CultureManagement" asp-controller="Home" method="post">
    <select name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList" onchange="this.form.submit();"></select>
</form>

Best/Views/Shared/_Layout.cshtml
@inject UserManager<BestUser> UserManager
@{
    var signUser = await UserManager.GetUserAsync(User);
    var isAdmin = false;
    if (signUser != null)
    {
        isAdmin = await UserManager.IsInRoleAsync(signUser, "Administrator");
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Best</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Best</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Campaigns" asp-action="Index">Campaigns</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topics" asp-action="Index">Topics</a>
                        </li>
                        @if (isAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin panel</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item d-flex align-items-center">
                            <partial name="_Culture" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Best - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/marked.min.js"></script>
    <script src="~/js/addInMarkdown.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>