Best/Controllers/ImgController.cs
using Best.Data.Interfaces;
using Best.Data.Interfaces.IImg;
using Best.Data.Models;
using Best.Data.Models.Img;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Best.Controllers
{
    public class ImgController : Controller
    {
        private readonly IPostImg _postImg;
        private readonly IPosts _posts;
        private readonly ICampaignImg _CampaignImg;
        private readonly ICampaigns _Campaigns;
        public ImgController(IPostImg postImg, IPosts posts, ICampaignImg CampaignImg, ICampaigns Campaigns)
        {
            _postImg = postImg;
            _posts = posts;
            _CampaignImg = CampaignImg;
            _Campaigns = Campaigns;
        }
        public async Task<IActionResult> IndexPostImg(Post post)
        {
            post = _posts.GetPostById(post.Id);
            return View(post);
        }
        public async Task<IActionResult> DeletePostImg(string id)
        {
            PostImg postImg = _postImg.GetImgById(id);
            await _postImg.DeleteImg(postImg);
            return RedirectToRoute(new { controller = "Posts", action = "Edit", id = postImg.Post.Id });//controller = "Post",action = "Edit",id = postImg.Post.Id});
        }
        public async Task<IActionResult> AddPostImgs(Post post)
        {
            var newpost = _posts.GetPostById(post.Id);
            newpost.ImgsFile = post.ImgsFile;
            if (newpost.ImgsFile != null) await _postImg.AddImgs(newpost);
            return RedirectToRoute(new { controller = "Posts", action = "Edit", id = post.Id });
        }
        public async Task<IActionResult> IndexCampaignImg(Campaign Campaign)
        {
            Campaign = _Campaigns.GetCampaignById(Campaign.Id);
            return View(Campaign);
        }
        public async Task<IActionResult> DeleteCampaignImg(string id)
        {
            CampaignImg CampaignImg = _CampaignImg.GetImgById(id);
            await _CampaignImg.DeleteImg(CampaignImg);
            return RedirectToRoute(new { controller = "Campaigns", action = "Edit", id = CampaignImg.Campaign.Id });//controller = "Post",action = "Edit",id = postImg.Post.Id});
        }
        public async Task<IActionResult> AddCampaignImgs(Campaign Campaign)
        {
            var newcampaign = _Campaigns.GetCampaignById(Campaign.Id);
            newcampaign.ImgsFile = Campaign.ImgsFile;
            if (newcampaign.ImgsFile != null) await _CampaignImg.AddImgs(newcampaign);
            return RedirectToRoute(new { controller = "Campaigns", action = "Edit", id = Campaign.Id });
        }

    }
}

Best/Views/Img/IndexCampaignImg.cshtml
@model Campaign

@{
    ViewData["Title"] = "Index";
}
<hr />
<h1>Carousel</h1>
<form asp-controller="Img" asp-action="AddCampaignImgs" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    <label asp-for="Carousel" class="control-label"></label>
    <input asp-for="ImgsFile" accept="image/*" />
    <input type="submit" value="Add imgs" class="btn btn-primary" />
</form>
<div class="card-columns">
    @foreach (var item in Model.Carousel)
    {
        <div class="card">
            <img class="card-img-top" src="@await _dropbox.getImgByUrl(item.Url)" alt="@item.Alt">
            <div class="card-body">
                @item.Alt
            </div>
            <a asp-controller="Img" asp-action="DeleteCampaignImg" asp-route-id="@item.Id" class="btn btn-danger">Delete img</a>
        </div>
    }
</div>

Best/Views/Img/IndexPostImg.cshtml
@model Post

@{
    ViewData["Title"] = "Index";
}
<hr />
<h1>Carousel</h1>
<form asp-controller="Img" asp-action="AddPostImgs" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    <label asp-for="Carousel" class="control-label"></label>
    <input asp-for="ImgsFile" accept="image/*" />
    <input type="submit" value="Add imgs" class="btn btn-primary" />
</form>
<div class="card-columns">
    @foreach (var item in Model.Carousel)
    {
        <div class="card">
            <img class="card-img-top" src="@await _dropbox.getImgByUrl(item.Url)" alt="@item.Alt">
            <div class="card-body">
                @item.Alt
            </div>
            <a asp-controller="Img" asp-action="DeletePostImg" asp-route-id="@item.Id" class="btn btn-danger">Delete img</a>
        </div>
    }
</div>